Repository ocamllabs/vscode-ocaml-platform, pull requests merged in 2023-10, with the labels that each got.

#1234 Yarn Workspace
  .github/workflows/main.yml
  .prettierrc.json
  .yarnrc
  Makefile
  astexplorer/package.json
  astexplorer/yarn.lock
  package.json
  yarn.lock
Labels: no changelog

#1235 opam 2.2
  .github/workflows/main.yml
  Makefile
  dune-project
  vscode-ocaml-platform.opam
  vscode.opam
Labels: no changelog

#1238 `vscode-test` -> `@vscode/test-electron`
  package.json
  test/runEsyTests.js
  test/runOpamTests.js
  test/runProblemMatcherTests.js
  yarn.lock
Labels: no changelog

#1240 Yarn v4
  .gitignore
  .yarn/releases/yarn-4.0.0.cjs
  .yarnrc
  .yarnrc.yml
  package.json
  yarn.lock
Labels: no changelog

#1241 Update ocamlformat to 0.26.1
  .ocamlformat
  dune-project
  vscode-ocaml-platform.opam
  vscode.opam
Labels: no changelog

#1242 Replace deprecated release actions
  .github/workflows/main.yml
Labels: no changelog

#1244 Remove redundant Dependabot configuration
  .github/dependabot.yml
Labels: no changelog

#1248 Remove import declarations for unused glob dep in test
  test/suite/esy.js
  test/suite/problems.js
Labels: no changelog

#1249 Clean up tests
  .github/workflows/main.yml
  .prettierignore
  dune
  package.json
  test/dune
  test/runEsyTests.js
  test/suite/esy.js
  test/suite/esy.test.js
  test/suite/opam.js
  test/suite/opam.test.js
  test/suite/problems.js
  tests/fixtures/dune
  tests/fixtures/sample-esy/.gitignore
  tests/fixtures/sample-esy/.vscode/settings.json
  tests/fixtures/sample-esy/bin/CamlUtil.ml
  tests/fixtures/sample-esy/bin/CamlUtil.mli
  tests/fixtures/sample-esy/bin/SampleEsyApp.ml
  tests/fixtures/sample-esy/bin/dune
  tests/fixtures/sample-esy/dune-project
  tests/fixtures/sample-esy/esy.json
  tests/fixtures/sample-esy/esy.lock/.gitattributes
  tests/fixtures/sample-esy/esy.lock/.gitignore
  tests/fixtures/sample-esy/esy.lock/index.json
  tests/fixtures/sample-esy/esy.lock/opam/base-threads.base/opam
  tests/fixtures/sample-esy/esy.lock/opam/base-unix.base/opam
  tests/fixtures/sample-esy/esy.lock/opam/biniou.1.2.1/opam
  tests/fixtures/sample-esy/esy.lock/opam/cppo.1.6.8/opam
  tests/fixtures/sample-esy/esy.lock/opam/csexp.1.5.1/opam
  tests/fixtures/sample-esy/esy.lock/opam/dune-build-info.2.9.1/opam
  tests/fixtures/sample-esy/esy.lock/opam/dune.2.9.1/opam
  tests/fixtures/sample-esy/esy.lock/opam/easy-format.1.3.2/opam
  tests/fixtures/sample-esy/esy.lock/opam/ocaml-lsp-server.1.9.0/opam
  tests/fixtures/sample-esy/esy.lock/opam/ocamlformat-rpc-lib.0.19.0/opam
  tests/fixtures/sample-esy/esy.lock/opam/pp.1.1.2/opam
  tests/fixtures/sample-esy/esy.lock/opam/ppx_yojson_conv_lib.v0.14.0/opam
  tests/fixtures/sample-esy/esy.lock/opam/re.1.10.3/opam
  tests/fixtures/sample-esy/esy.lock/opam/result.1.5/opam
  tests/fixtures/sample-esy/esy.lock/opam/seq.base/files/META.seq
  tests/fixtures/sample-esy/esy.lock/opam/seq.base/files/seq.install
  tests/fixtures/sample-esy/esy.lock/opam/seq.base/opam
  tests/fixtures/sample-esy/esy.lock/opam/sexplib0.v0.14.0/opam
  tests/fixtures/sample-esy/esy.lock/opam/spawn.v0.14.0/opam
  tests/fixtures/sample-esy/esy.lock/opam/yojson.1.7.0/opam
  tests/fixtures/sample-esy/sample-esy.opam
  tests/fixtures/sample-opam/foo.ml
  tests/fixtures/sample-opam/main.ml
  tests/fixtures/sample-opam/sample-opam.opam
  tests/runBasicTests.js
  tests/runEsyTests.js
  tests/runOpamTests.js
  tests/suite/basic/index.js
  tests/suite/basic/problems.test.js
  tests/suite/esy/index.js
  tests/suite/esy/languageId.test.js
  tests/suite/opam/index.js
  tests/suite/opam/languageId.test.js
  yarn.lock
Labels: no changelog

#1251 Update `gen_js_api` to 1.1.2
  dune-project
  vscode-ocaml-platform.opam
  vscode.opam
Labels: dependencies, no changelog

#1253 Remove xvfb action as xvfb is now installed by default
  .github/workflows/main.yml
Labels: no changelog

#1252 Prepare 1.13.3
  CHANGELOG.md
  package.json
  yarn.lock
Labels: no changelog

#1256 Simplify gen_js_api bindings
  src-bindings/interop/interop.ml
  src-bindings/interop/interop.mli
  src-bindings/node/node.mli
  src-bindings/polka/polka.mli
  src-bindings/vscode/vscode.ml
  src-bindings/vscode/vscode.mli
  src-bindings/vscode_languageclient/vscode_languageclient.mli
  src/cm_editor.ml
  src/treeview_sandbox.ml
Labels: no changelog

#1257 Fix the build status badge
  README.md
Labels: type: documentation, no changelog

#1264 Move the analysis action to a separate workflow
  .github/workflows/analysis.yml
  .github/workflows/main.yml
Labels: no changelog

#1265 Rename the main workflow
  .github/workflows/main.yml
Labels: no changelog

#1263 Prepare 1.13.4
  .yarnrc.yml
  CHANGELOG.md
  package.json
  yarn.lock
Labels: no changelog

#1266 Set `cancel-in-progress` to false for the `analysis` concurrency group
  .github/workflows/analysis.yml
Labels: no changelog
