Repository ocamllabs/vscode-ocaml-platform, pull requests merged in 2023-07, with the labels that each got.

#1164 Update Action to check the right file
  .github/workflows/changelog.yml
Labels: no changelog

#1157 Support lsp server settings
  CHANGELOG.md
  package.json
  src-bindings/vscode/vscode.ml
  src-bindings/vscode/vscode.mli
  src-bindings/vscode_languageclient/vscode_languageclient.ml
  src-bindings/vscode_languageclient/vscode_languageclient.mli
  src/settings.ml
  src/settings.mli
  src/vscode_ocaml_platform.ml
Labels: type: feature

#1161 Preserve focus when sending to repl
  CHANGELOG.md
  src/extension_instance.ml
  src/repl.ml
  src/terminal_sandbox.ml
  src/terminal_sandbox.mli
Labels: type: improvement

#1165 Add more patterns to `opam-metadata.source`
  CHANGELOG.md
  syntaxes/dune-project.json
Labels: type: syntax highlighting

#1148 OCaml earlybird debugger
  CHANGELOG.md
  README.md
  package.json
  src-bindings/vscode/vscode.ml
  src-bindings/vscode/vscode.mli
  src/ast_editor.ml
  src/cmd.ml
  src/cmd.mli
  src/earlybird.ml
  src/earlybird.mli
  src/extension_commands.ml
  src/extension_consts.ml
  src/import.ml
  src/terminal_sandbox.ml
  src/vscode_ocaml_platform.ml
Labels: type: feature

#1179 chore: prepare 1.13.0
  package.json
Labels: no changelog

#1177 chore: update deps
  package.json
  yarn.lock
Labels: no changelog

#1178 chore: fix build task
  .vscode/tasks.json
Labels: no changelog
