Repository ocamllabs/vscode-ocaml-platform, pull requests merged in 2024-03, with the labels that each got.

#1398 Fix opening a new REPL terminal after first one was terminated
  CHANGELOG.md
  src/repl.ml
Labels: type: bug

#1402 Update promise_jsoo to 0.4.2
  src-bindings/vscode/vscode.ml
  src-bindings/vscode/vscode.mli
Labels: no changelog

#1396 Adopt modern packaging techniques
  astexplorer/package.json
  package.json
Labels: no changelog

#1403 Reduce use of Js.Unit module
  src-bindings/interop/interop.ml
  src-bindings/vscode/vscode.ml
  src-bindings/vscode/vscode.mli
  src/cm_editor.ml
Labels: no changelog

#1331 fallback to ocaml.org documentation page
  CHANGELOG.md
  package.json
  src/treeview_sandbox.ml
  src/treeview_switches.ml
Labels: type: improvement

#1427 Fix `sideEffects` field in `astexplorer/package.json`
  CHANGELOG.md
  astexplorer/package.json
Labels: type: bug
