Repository ocamllabs/vscode-ocaml-platform, pull requests merged in 2024-11, with the labels that each got.

#1648 Refactor
  dune-project
  src/extension_commands.ml
  src/ocaml_lsp.ml
  src/sandbox.ml
  vscode-ocaml-platform.opam
  vscode.opam
Labels: no changelog

#1649 Update GitHub Actions workflow
  .github/workflows/main.yml
Labels: no changelog

#1650 Fix cwd formatting on windows
  CHANGELOG.md
  src/extension_instance.ml
Labels: type: bug

#1656 Update Yarn to 4.5.2
  package.json
  yarn.lock
Labels: no changelog

#1661 Update Yarn to 4.5.3
  package.json
  yarn.lock
Labels: no changelog

#1654 Jump Custom Request Client Implementation
  CHANGELOG.md
  package.json
  src/custom_requests.ml
  src/custom_requests.mli
  src/extension_commands.ml
  src/extension_consts.ml
  src/ocaml_lsp.ml
  src/ocaml_lsp.mli
  src/treeview_commands.ml
Labels: type: feature
