Repository ocamllabs/vscode-ocaml-platform, pull requests merged in 2024-01, with the labels that each got.

#1324 pass --no-dependencies to vsce package
  Makefile
Labels: no changelog

#1322 recompute env dict on every command
  CHANGELOG.md
  src-bindings/node/node.ml
  src-bindings/node/node.mli
  src/extension_instance.ml
Labels: type: bug

#1330 remove unnecessary activationEvents entries
  package.json
Labels: no changelog

#1321 Notify LSP of workspace config when starting
  CHANGELOG.md
  src/extension_instance.ml
  src/extension_instance.mli
  src/vscode_ocaml_platform.ml
Labels: type: bug

#1320 Add `ocaml.server.duneDiagnostics` to disable dune diagnostics reporting
  CHANGELOG.md
  package.json
  src-bindings/vscode_languageclient/vscode_languageclient.ml
  src-bindings/vscode_languageclient/vscode_languageclient.mli
  src/extension_instance.ml
  src/extension_instance.mli
  src/settings.ml
  src/settings.mli
  src/vscode_ocaml_platform.ml
Labels: type: feature, ocamllsp

#1334 Fix broken syntax highlighting for a wildcard in the env stanza
  CHANGELOG.md
  syntaxes/dune.json
Labels: type: bug, type: syntax highlighting

#1342 Prettier -> Biome
  .github/workflows/main.yml
  .prettierignore
  .prettierrc.json
  .vscode/launch.json
  .vscode/tasks.json
  biome.json
  languages/dune.json
  languages/menhir.json
  languages/ocaml.json
  languages/ocamlbuild.json
  languages/ocamllex.json
  languages/opam-install.json
  languages/opam.json
  languages/reason.json
  package.json
  src-bindings/node/node_stub.js
  tests/suite/basic/problems.test.ts
  tests/suite/opam/languageId.test.ts
  yarn.lock
Labels: no changelog

#1343 Update syntax for ocamlformat
  CHANGELOG.md
  syntaxes/ocamlformat.json
Labels: type: syntax highlighting

#1313 Add Syntax Documentation to vscode
  CHANGELOG.md
  package.json
  src/extension_instance.ml
  src/extension_instance.mli
  src/ocaml_lsp.ml
  src/ocaml_lsp.mli
  src/settings.ml
  src/settings.mli
  src/vscode_ocaml_platform.ml
Labels: type: feature, ocamllsp

#1355 Fix improper coloring of ocamldoc comments
  CHANGELOG.md
  syntaxes/ocaml.json
Labels: type: bug, type: syntax highlighting

#1369 Fix md code block bug
  CHANGELOG.md
  syntaxes/ocaml-markdown-codeblock.json
  syntaxes/reason-markdown-codeblock.json
Labels: type: bug, type: syntax highlighting

#1365 Add syntax color to ocamldoc markup
  CHANGELOG.md
  syntaxes/ocamldoc.json
Labels: type: improvement, type: syntax highlighting
