Repository ocamllabs/vscode-ocaml-platform, pull requests merged in 2024-12, with the labels that each got.

#1668 Update ocamlformat to 0.27.0
  .ocamlformat
  dune-project
  src/ast_editor.ml
  src/ocaml_lsp.ml
  src/odig.ml
  src/ppx_tools/dumpast.mli
  src/ppx_tools/traverse_ast2.ml
  src/sandbox.mli
Labels: no changelog

#1669 Chores
  .github/workflows/main.yml
  Makefile
Labels: no changelog

#1670 Use DeterminateSystems/update-flake-lock in CI
  .github/workflows/dependency-review.yml
  .github/workflows/nix.yml
  .github/workflows/update-flake-lock.yml
Labels: no changelog

#1673 Make construct chaining configurable
  CHANGELOG.md
  README.md
  package.json
  src/extension_commands.ml
  src/settings.ml
  src/settings.mli
Labels: type: feature

#1667 Update dune to 3.17
  dune-project
  vscode-ocaml-platform.opam
  vscode.opam
Labels: no changelog

#1626 Search By Type or Polarity
  CHANGELOG.md
  README.md
  package.json
  src-bindings/vscode/vscode.ml
  src-bindings/vscode/vscode.mli
  src/custom_requests.ml
  src/custom_requests.mli
  src/extension_commands.ml
  src/extension_consts.ml
  src/import.ml
  src/ocaml_lsp.ml
  src/ocaml_lsp.mli
  src/treeview_commands.ml
  src/treeview_help.ml
  src/treeview_sandbox.ml
  src/treeview_switches.ml
Labels: type: feature

#1666 Navigating Typed Holes
  CHANGELOG.md
  package.json
  src/extension_commands.ml
  src/extension_consts.ml
  src/settings.ml
  src/settings.mli
  src/treeview_commands.ml
Labels: type: feature

#1694 Fix bug
  src/extension_commands.ml
Labels: type: bug, no changelog

#1695 Display message instead of empty list
  CHANGELOG.md
  src/extension_commands.ml
Labels: type: improvement
