Repository ocamllabs/vscode-ocaml-platform, pull requests merged in 2025-07, with the labels that each got.

#1873 Bump gen_js_api from 1.1.4 to 1.1.5
  dune-project
  vscode-interop.opam
  vscode-node.opam
  vscode-ocaml-platform.opam
  vscode.opam
Labels: no changelog

#1871 Reintroduce quoted string literal highlighting with correct ID handling
  CHANGELOG.md
  syntaxes/mlx.json
  syntaxes/ocaml.json
Labels: type: bug, type: syntax highlighting

#1791 Automatically configure Dune Package Management
  CHANGELOG.md
  package.json
  src/cm_editor.ml
  src/dune.ml
  src/dune.mli
  src/dune_formatter.ml
  src/dune_task_provider.ml
  src/earlybird.ml
  src/extension_commands.ml
  src/extension_consts.ml
  src/extension_instance.ml
  src/extension_instance.mli
  src/odig.ml
  src/repl.ml
  src/sandbox.ml
  src/sandbox.mli
  src/terminal_sandbox.ml
Labels: type: feature, type: improvement

#1887 Upgrade to ppxlib 0.36.0
  dune-project
  src/ppx_tools/traverse_ast.ml
  src/ppx_tools/traverse_ast2.ml
  vscode-ocaml-platform.opam
Labels: no changelog
