Repository ocamllabs/vscode-ocaml-platform, pull requests merged in 2025-01, with the labels that each got.

#1698 Update bindings
  src-bindings/node/node.ml
  src-bindings/node/node_stub.js
  src-bindings/polka/polka_stub.js
  src-bindings/vscode/vscode_stub.js
  src-bindings/vscode_languageclient/vscode_languageclient_stub.js
Labels: no changelog

#1675 New command: Type of dynamic selection
  CHANGELOG.md
  package.json
  src-bindings/vscode/vscode.ml
  src-bindings/vscode/vscode.mli
  src/ast_editor.ml
  src/custom_requests.ml
  src/custom_requests.mli
  src/extension_commands.ml
  src/extension_consts.ml
  src/extension_instance.ml
  src/extension_instance.mli
  src/import.ml
  src/ocaml_lsp.ml
  src/ocaml_lsp.mli
  src/output.ml
  src/type_selection.ml
  src/vscode_ocaml_platform.ml
Labels: type: feature

#1710 Remove uses of `Handlers` in type of selection
  src/ast_editor.ml
  src/import.ml
  src/type_selection.ml
Labels: no changelog

#1685 Add reason language to ast_editor
  CHANGELOG.md
  src/ast_editor.ml
Labels: type: improvement, reasonml
